# ==============================================================================
# Description: Added a 20GB secondary EBS volume (/dev/sdm) for persistent data storage.
# Revision number: 1.1
# Date: May 24, 2026
# ==============================================================================

AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Elastic Compute Cloud (EC2) Template

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance"

  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Description: "The Subnet ID where the EC2 instance should be launched"

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp2
            DeleteOnTermination: false
            VolumeSize: 20